/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;


import config.conf;
import java.awt.Color;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import main.login;
import masterlist.servicemasterlist;
import masterlist.barbersdashboard;
/**
 *
 * @author USER34
 */
public class admindashboard extends javax.swing.JFrame {

    /**
     * Creates new form admindashboard
     */
  public admindashboard() {

    if (config.session.a_id == 0) {

        JOptionPane.showMessageDialog(null, "Please login first!");
        new login().setVisible(true);
        dispose();
        return;
    }

    initComponents();
    name.setText(config.session.username);

    loadTransactions(); // 🔥 IMPORTANT
}
    
    Color navcolor = new Color (204,204,204);
    Color headercolor = new Color (204,204,204);
    Color bodycolor = new Color (102,102,102);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        dashpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        accountpanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        bookspanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        transactionpanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        maindesktop = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 0, 153));
        jPanel2.setLayout(null);

        header.setBackground(new java.awt.Color(102, 102, 102));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ADMIN DASHBOARB");
        header.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 470, 30));

        dashpanel.setBackground(new java.awt.Color(204, 204, 204));
        dashpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashpanelMouseExited(evt);
            }
        });
        dashpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DASHBOARD");
        dashpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 130, 28));

        header.add(dashpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 50));

        userpanel.setBackground(new java.awt.Color(204, 204, 204));
        userpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userpanelMouseExited(evt);
            }
        });
        userpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("USER");
        userpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 60, 28));

        header.add(userpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 70, 50));

        accountpanel.setBackground(new java.awt.Color(204, 204, 204));
        accountpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accountpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accountpanelMouseExited(evt);
            }
        });
        accountpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ACCOUNT");
        accountpanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 150, 28));

        header.add(accountpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 140, 50));

        bookspanel.setBackground(new java.awt.Color(204, 204, 204));
        bookspanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookspanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookspanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookspanelMouseExited(evt);
            }
        });
        bookspanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BARBER");
        bookspanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 80, 28));

        header.add(bookspanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 80, 50));

        transactionpanel.setBackground(new java.awt.Color(204, 204, 204));
        transactionpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transactionpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transactionpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                transactionpanelMouseExited(evt);
            }
        });
        transactionpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PAYMENT TRANSACTION");
        transactionpanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 230, 28));

        header.add(transactionpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 240, 50));
        header.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 14, 150, 30));

        jPanel2.add(header);
        header.setBounds(0, 0, 740, 110);

        maindesktop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setText("EDIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        maindesktop.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 113, 70, 40));

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        maindesktop.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 70, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "costumer", "barber", "amount", "payment date", "payment method", "status", "service"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        maindesktop.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 650, 310));

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        maindesktop.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 70, 40));

        jButton4.setBackground(new java.awt.Color(153, 153, 153));
        jButton4.setText("SERVICE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        maindesktop.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 30));

        jButton5.setBackground(new java.awt.Color(153, 153, 153));
        jButton5.setText("LOGOUT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        maindesktop.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, 40));

        jToggleButton1.setText("LOGS");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        maindesktop.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 70, 30));

        jPanel2.add(maindesktop);
        maindesktop.setBounds(0, 60, 740, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void accountpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountpanelMouseExited
        accountpanel.setBackground(navcolor);
    }//GEN-LAST:event_accountpanelMouseExited

    private void accountpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountpanelMouseEntered
        accountpanel.setBackground(bodycolor);
    }//GEN-LAST:event_accountpanelMouseEntered

    private void accountpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountpanelMouseClicked
        userForm us = new userForm();
        us.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_accountpanelMouseClicked

    private void transactionpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionpanelMouseExited
        transactionpanel.setBackground(navcolor);
    }//GEN-LAST:event_transactionpanelMouseExited

    private void transactionpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionpanelMouseEntered
        transactionpanel.setBackground(bodycolor);
    }//GEN-LAST:event_transactionpanelMouseEntered

    private void bookspanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookspanelMouseExited
        bookspanel.setBackground(navcolor);
    }//GEN-LAST:event_bookspanelMouseExited

    private void bookspanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookspanelMouseEntered
        bookspanel.setBackground(bodycolor);
    
    }//GEN-LAST:event_bookspanelMouseEntered

    private void userpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userpanelMouseExited
        userpanel.setBackground(navcolor);
    }//GEN-LAST:event_userpanelMouseExited

    private void userpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userpanelMouseEntered
        userpanel.setBackground(bodycolor);
    }//GEN-LAST:event_userpanelMouseEntered

    private void userpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userpanelMouseClicked
        userstable us = new userstable();
        us.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userpanelMouseClicked

    private void dashpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashpanelMouseExited
        dashpanel.setBackground(navcolor);
    }//GEN-LAST:event_dashpanelMouseExited

    private void dashpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashpanelMouseEntered
        dashpanel.setBackground(bodycolor);
        
    }//GEN-LAST:event_dashpanelMouseEntered

    private void transactionpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionpanelMouseClicked
            transaction tr = new transaction();
    tr.setVisible(true);
    this.dispose();

    }//GEN-LAST:event_transactionpanelMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         int row = jTable1.getSelectedRow();

if(row == -1){
    JOptionPane.showMessageDialog(null, "Select a row first!");
    return;
}

int id = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
String customer = jTable1.getValueAt(row, 1).toString();
String barber = jTable1.getValueAt(row, 2).toString();
String amount = jTable1.getValueAt(row, 3).toString();
String paymentDate = jTable1.getValueAt(row, 4).toString();
String paymentMethod = jTable1.getValueAt(row, 5).toString();
String status = jTable1.getValueAt(row, 6).toString();
String service = jTable1.getValueAt(row, 7).toString();

transaction tr = new transaction(id, customer, barber, amount,
        paymentDate, paymentMethod, status, service);

tr.setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      transaction tr = new transaction(); // open blank form
    tr.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          int row = jTable1.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select a row first!");
        return;
    }

    int id = Integer.parseInt(jTable1.getValueAt(row, 0).toString());

    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete this transaction?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION
    );

    if (confirm == JOptionPane.YES_OPTION) {
        try {
            conf c = new conf();

            String sql = "DELETE FROM transactions WHERE id = " + id;
            c.deleteRecord(sql);

            JOptionPane.showMessageDialog(this, "Deleted successfully!");

            loadTransactions(); // refresh table

        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    servicemasterlist sm = new servicemasterlist();
    sm.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to logout?",
            "Logout",
            JOptionPane.YES_NO_OPTION
    );

    if(confirm == JOptionPane.YES_OPTION){

        // clear session
        config.session.a_id = 0;
        config.session.username = null;
        config.session.email = null;
        config.session.type = null;
        config.session.status = null;

        // balik sa login form
        login lg = new login();
        lg.setVisible(true);

        // close dashboard
        this.dispose();
    }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void bookspanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookspanelMouseClicked
         barbers b = new barbers();
    b.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_bookspanelMouseClicked

    private void dashpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashpanelMouseClicked
       barbersdashboard bd = new barbersdashboard();
    bd.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_dashpanelMouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        logs lg = new logs(); // open logs page
    lg.setVisible(true);
    this.dispose(); // close current dashboard
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     */
    public void loadTransactions() {
    try {
        conf c = new conf();
        c.displayData("SELECT * FROM transactions", jTable1); // assumes displayData fills the table
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error loading transactions: " + e.getMessage());
    }
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admindashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admindashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admindashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admindashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admindashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accountpanel;
    private javax.swing.JPanel bookspanel;
    private javax.swing.JPanel dashpanel;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JDesktopPane maindesktop;
    private javax.swing.JLabel name;
    private javax.swing.JPanel transactionpanel;
    private javax.swing.JPanel userpanel;
    // End of variables declaration//GEN-END:variables
}
