/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package masterlist;

import admin.masterlist;
import admin.admindashboard;
import config.conf;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Admin
 */
public final class servicemasterlist extends javax.swing.JFrame {

    /**
     * Creates new form servicemasterlist
     */
    public servicemasterlist() {
        initComponents();
         loadData();
    }
public void loadData() {
    try {
        config.conf c = new config.conf();
        java.sql.ResultSet rs = c.masterlist("SELECT * FROM services");

        javax.swing.table.DefaultTableModel model =
                (javax.swing.table.DefaultTableModel) jTable1.getModel();

        model.setRowCount(0);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id"),
                rs.getString("service_name"),
                rs.getDouble("price"),
                rs.getString("description")
            });
        }

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(null, e.getMessage());
    }
} // ✅ IMPORTANT: MAY CLOSING BRACKET DITO
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "service name", "price", "discription"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 640, 320));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setText("service name");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 140, -1));

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setText("add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setText("edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        jButton4.setBackground(new java.awt.Color(153, 153, 153));
        jButton4.setText("delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        jButton5.setBackground(new java.awt.Color(153, 153, 153));
        jButton5.setText("back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 150, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\final logo.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 680, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         masterlist ml = new masterlist(this); // ipapasa ang current form
    ml.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    admindashboard ad = new admindashboard();
    ad.setVisible(true);
    this.dispose(); // close current form
    
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         int row = jTable1.getSelectedRow();

    if(row < 0){
        JOptionPane.showMessageDialog(null, "Please select a service to edit!");
        return;
    }

    try{
        int id = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
        String service = jTable1.getValueAt(row, 1).toString();
        String price = jTable1.getValueAt(row, 2).toString();
        String description = jTable1.getValueAt(row, 3).toString();

        String newService = JOptionPane.showInputDialog("Edit Service Name:", service);
        String newPrice = JOptionPane.showInputDialog("Edit Price:", price);
        String newDesc = JOptionPane.showInputDialog("Edit Description:", description);

        if(newService == null || newPrice == null || newDesc == null){
            return;
        }

        double priceValue = Double.parseDouble(newPrice);

        config.conf c = new config.conf();
        java.sql.Connection conn = c.getConnection();

        String sql = "UPDATE services SET service_name=?, price=?, description=? WHERE id=?";
        java.sql.PreparedStatement ps = conn.prepareStatement(sql);

        ps.setString(1, newService);
        ps.setDouble(2, priceValue);
        ps.setString(3, newDesc);
        ps.setInt(4, id);

        ps.executeUpdate();

        JOptionPane.showMessageDialog(null, "Service Updated Successfully!");
        loadData();

        ps.close();
        conn.close();

    } catch(Exception e){
        JOptionPane.showMessageDialog(null, "Edit Failed: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         int row = jTable1.getSelectedRow();

    if(row < 0){
        javax.swing.JOptionPane.showMessageDialog(null, "Please select a service to delete!");
        return;
    }

    int confirm = javax.swing.JOptionPane.showConfirmDialog(
            null, 
            "Are you sure you want to delete this service?", 
            "Confirm Delete", 
            javax.swing.JOptionPane.YES_NO_OPTION
    );

    if(confirm != javax.swing.JOptionPane.YES_OPTION){
        return;
    }

    try {
        int id = Integer.parseInt(jTable1.getValueAt(row, 0).toString());

        config.conf c = new config.conf();
        java.sql.Connection conn = c.getConnection();

        if(conn == null){
            JOptionPane.showMessageDialog(null, "Database connection failed!");
            return;
        }

        String sql = "DELETE FROM services WHERE id=?";
        java.sql.PreparedStatement ps = conn.prepareStatement(sql);
        ps.setInt(1, id);
        int deleted = ps.executeUpdate();

        if(deleted > 0){
            JOptionPane.showMessageDialog(null, "Service deleted successfully!");
        } else {
            JOptionPane.showMessageDialog(null, "No record found to delete!");
        }

        loadData(); // Refresh table

    } catch(Exception e){
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(null, "Delete failed: " + e.getMessage());
    }
    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         // Open masterlist form and pass 'this' as parent for table refresh
    masterlist ml = new masterlist(this);
    ml.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
     try {
        config.conf c = new config.conf();
        String sql = "SELECT * FROM services WHERE service_name LIKE ?";
        java.sql.Connection conn = c.getConnection();
        java.sql.PreparedStatement ps = conn.prepareStatement(sql);
         String keyword = null;
        ps.setString(1, "%" + keyword + "%"); // search keyword
        java.sql.ResultSet rs = ps.executeQuery();

        javax.swing.table.DefaultTableModel model =
                (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // clear table

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id"),
                rs.getString("service_name"),
                rs.getDouble("price"),
                rs.getString("description")
            });
        }

        rs.close();
        ps.close();
        conn.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Search failed: " + e.getMessage());
    }    
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(servicemasterlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(servicemasterlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(servicemasterlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(servicemasterlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new servicemasterlist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void displayUsers() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
